theme: jekyll-theme-minimal
logo: 
title: [Zubaer Ahmed]
description: [It is zubaer ahmed and this is a fake identity]
email: zubaerahmed00@gmail.com
show_downloads: false
google_analytics:
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

